force-app/main/default/objects/Customer_New__c/Customer_New__c.object-meta.xml
<CustomObject>
    <label>Customer New</label>
    <nameField>
        <label>Customer New Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers New</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_New__c/fields/Customer_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Description__c</fullName>
    <label>Customer Description</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_New__c/fields/Customer_New_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_New_Type__c</fullName>
    <label>Customer New Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
                <default>true</default>
                <label>B</label>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FirstClass.cls
public class FirstClass {
    public static final Map<String,String> customerType = new Map<String,String>{
        'A'=>'A type',
        'B'=>'B type',
        'C'=>'C type'
    };

    public static void myMethod(){
        List<Customer_New__c> listCustomerNew = [select name from Customer_New__c];
        for (Customer_New__c customer_new : listCustomerNew) {
            System.debug(customer_new.Name);
            System.debug(customer_new.Customer_New_Type__c);
            
            customer_new.Customer_Description__c = customerType.get(customer_new.Customer_New_Type__c);
        }
        update listCustomerNew;
        
    }
}